# Generated by Django 4.2 on 2024-02-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('hero_class', models.CharField(max_length=20)),
                ('creation_data', models.DateTimeField(verbose_name='Время создания')),
                ('health', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=100)),
                ('defence', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=1000)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavern_of_heroes.hero')),
            ],
        ),
    ]
