# Generated by Django 4.2 on 2024-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern_of_heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='creation_data',
            field=models.DateTimeField(verbose_name='Creation data'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_class',
            field=models.CharField(choices=[('W', 'Воин'), ('M', 'Маг'), ('A', 'Лучник'), ('T', 'Вор')], max_length=1),
        ),
    ]
