# Generated by Django 4.2 on 2024-02-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern_of_heroes', '0002_alter_hero_creation_data_alter_hero_hero_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Armor', 'Armor'), ('Helmet', 'Helmet'), ('Gloves', 'Gloves'), ('Boots', 'Boots'), ('Weapon', 'Weapon'), ('Special', 'Special')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='gold',
            field=models.IntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='hero',
            name='list_of_items',
            field=models.ManyToManyField(to='tavern_of_heroes.item'),
        ),
    ]
