# Generated by Django 4.2 on 2024-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern_of_heroes', '0006_alter_hero_creation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='creation_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
